# Generated by Django 6.0 on 2025-12-11 15:01

import Participant.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='cin',
            field=models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='CIN must be exactly 8 digits.', regex='^[0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[Participant.models.email_validator]),
        ),
    ]
