# Generated by Django 6.0 on 2025-12-11 15:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorie', '0002_alter_category_options_alter_category_title'),
        ('Conference', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='description',
        ),
        migrations.AlterField(
            model_name='conference',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='program',
            field=models.FileField(blank=True, null=True, upload_to='programs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__gt', datetime.date(2025, 12, 11))), name='start_date_must_be_future'),
        ),
    ]
