# Generated by Django 6.0 on 2025-12-11 15:03

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0003_remove_conference_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='program',
            field=models.FileField(blank=True, null=True, upload_to='programs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
